SuperheroCreator/Models/ErrorViewModel.cs
using System;

namespace SuperheroCreator.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperheroCreator/Models/PrimaryAbility.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperheroCreator.Models
{
    public class PrimaryAbility
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

SuperheroCreator/Models/SecondaryAbility.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperheroCreator.Models
{
    public class SecondaryAbility
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

SuperheroCreator/Models/Superhero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SuperheroCreator.Models
{
    public class Superhero
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string AlterEgo { get; set; }
        public string CatchPhrase { get; set; }
        public string PrimaryAbility { get; set; }
        public string SecondaryAbility { get; set; }

        //[ForeignKey("PrimarySuperHeroAbility")]
        //public int PrimaryAbilityId { get; set; }
        //public PrimaryAbility PrimarySuperHeroAbility { get; set; }

        //[ForeignKey("SecondarySuperHeroAbility")]
        //public int SecondaryAbilityId { get; set; }
        //public SecondaryAbility SecondarySuperHeroAbility { get; set; }
        
    }
}

SuperheroCreator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperheroCreator.Models;

namespace SuperheroCreator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperheroCreator/Controllers/SuperheroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SuperheroCreator.Data;
using SuperheroCreator.Models;

namespace SuperheroCreator.Controllers
{
    public class SuperheroesController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SuperheroesController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Superheroes
        public ActionResult Index()
        {
            var heroes = _context.Superheroes;
            return View(heroes);
        }

        // GET: Superheroes/Details/5
        public ActionResult Details(int id)
        {
            var hero = _context.Superheroes.Where(a => a.Id == id).SingleOrDefault();
            return View(hero);
        }

        // GET: Superheroes/Create
        public ActionResult Create()
        {
            Superhero superhero = new Superhero();
            return View(superhero);
        }

        // POST: Superheroes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind ("Name,AlterEgo,CatchPhrase,PrimaryAbility,SecondaryAbility")]Superhero superhero)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Superheroes.Add(superhero);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(superhero);
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Superheroes/Edit/5
        public ActionResult Edit(int id)
        {
            var hero = _context.Superheroes.Where(a => a.Id == id).SingleOrDefault();
            return View(hero);
        }

        // POST: Superheroes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Superhero superhero)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var hero = _context.Superheroes.Where(a => a.Id == id).SingleOrDefault();
                    hero.Name = superhero.Name;
                    hero.PrimaryAbility = superhero.PrimaryAbility;
                    hero.SecondaryAbility = superhero.SecondaryAbility;
                    hero.CatchPhrase = superhero.CatchPhrase;
                    hero.AlterEgo = superhero.AlterEgo;
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(superhero);
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Superheroes/Delete/5
        public ActionResult Delete(int id)
        {
            var hero = _context.Superheroes.Where(a => a.Id == id).SingleOrDefault();
            return View(hero);
        }

        // POST: Superheroes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Superhero superhero)
        {
            try
            {
                _context.Superheroes.Remove(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperheroCreator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <img class="col-sm-12" src="~/images/spiderverse.jpg" alt="spiderman" />
        
    </div>

SuperheroCreator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperheroCreator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Superheroes" asp-action="Index">Superhero Creator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Superheroes" asp-action="Index">List View</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SuperheroCreator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SuperheroCreator/Views/Superheroes/Create.cshtml
@model SuperheroCreator.Models.Superhero

@{
    ViewData["Title"] = "Create";
}
<br />
<h1>Create</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group was-validated">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" type="text" class="form-control is-invalid" id="Name" placeholder="Name" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label">Alter Ego</label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label">Primary Superhero Ability</label>
                <input asp-for="PrimaryAbility"class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label">Secondary Superhero Ability</label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label">Catchphrase</label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success" /> |
                <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperheroCreator/Views/Superheroes/Delete.cshtml
@model SuperheroCreator.Models.Superhero

@{
    ViewData["Title"] = "Delete";
}
<br />
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
        <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
    </form>
</div>

SuperheroCreator/Views/Superheroes/Details.cshtml
@model SuperheroCreator.Models.Superhero

@{
    ViewData["Title"] = "Details";
}
<br />
<h1>Details</h1>

<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id ="@Model.Id" class="btn btn-outline-success">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
</div>

SuperheroCreator/Views/Superheroes/Edit.cshtml
@model SuperheroCreator.Models.Superhero

@{
    ViewData["Title"] = "Edit";
}
<br />
<h1>Edit</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" class="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group was-validated">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" type="text" class="form-control is-invalid" id="Name" placeholder="Name" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label"></label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label"></label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label"></label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-warning" /> |
                <a asp-action="Index" class="btn btn-outline-info">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperheroCreator/Views/Superheroes/Index.cshtml
@model IEnumerable<SuperheroCreator.Models.Superhero>

@{
    ViewData["Title"] = "List View";
}
<br>
<h1>Superheroes</h1>

<p>
    <a class="btn btn-outline-dark" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Name, "Details", new { id = item.Id })
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>